routes/web.php
<?php

use App\Http\Controllers\JointTripController;
use App\Http\Controllers\JointTripIndexController;
use App\Http\Controllers\JointTripUpdateController;
use App\Http\Controllers\TripController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CityController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\SightController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Api\CityController as ApiCityController;
use App\Http\Controllers\Api\CarouselCityController as ApiCarouselCityController;
use App\Http\Controllers\Api\CarouselSightController as ApiCarouselSightController;
use App\Http\Controllers\Api\ImageController as ApiImageController;
use App\Http\Controllers\Admin\CityController as AdminCityController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\ImageController as AdminImageController;
use App\Http\Controllers\Admin\SightController as AdminSightController;
use App\Http\Controllers\Admin\ArticleController as AdminArticleController;
use App\Http\Controllers\Admin\CommentController as AdminCommentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::view('/', 'index')->name('index');

Route::group(['middleware' => 'auth'], function () {

    Route::match(['get', 'post'], '/account', [AccountController::class, 'index'])->name('account');
    Route::match(['get', 'post'], '/account/profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::get('/account/trip', [AccountController::class, 'trip'])->name('account.trip');
    Route::match(['get', 'post'], '/profile', [ProfileController::class, 'store'])->name('profile.store');
    Route::match(['get', 'post'], '/driver', [DriverController::class, 'store'])->name('driver.store');

    Route::get('/trip', [TripController::class, 'index'])->name('trip');
    Route::post('/trip-registration', [JointTripIndexController::class, 'index'])->name('joint-trip');
    Route::put('/trip-registration/{id}', [JointTripUpdateController::class, 'update'])->name('joint-update');
    Route::resource('/joint', JointTripController::class);
    Route::post('/comments', [CommentController::class, 'store'])->name('comments.store');

    Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
        Route::get('/', function () {
            return redirect()->route('admin.cities.index');
        })->name('index');
        Route::resource('/cities', AdminCityController::class)->except(['show']);
        Route::resource('/sights', AdminSightController::class)->except(['show']);
        Route::resource('/articles', AdminArticleController::class)->except(['show']);
        Route::resource('/images', AdminImageController::class)->except(['show', 'edit', 'update']);
        Route::resource('/users', AdminUserController::class)->except(['show']);
        Route::resource('/comments', AdminCommentController::class)->only(['index', 'destroy']);
    });
});

Route::group(['as' => 'api.', 'prefix' => 'api'], function () {
    Route::get('/cities', [ApiCityController::class, 'index']);
    Route::get('/cityList', [ApiCityController::class, 'cityList']);
    Route::get('/carousel/City/{id}', [ApiCarouselCityController::class, 'index']);
    Route::get('/carousel/Sight/{id}', [ApiCarouselSightController::class, 'index']);
    Route::post('/images/store', [ApiImageController::class, 'store'])->name('images.store');
});

Route::group(['as' => 'cities.', 'prefix' => 'cities'], function () {
    Route::get('/{city:slug}', [CityController::class, 'index'])->name('index');
});

Route::group(['as' => 'sights.', 'prefix' => 'cities'], function () {
    Route::get('/{city:slug}/{sight:slug}', [SightController::class, 'index'])->name('index');
});

resources/views/accountTrip.blade.php
@extends('layouts.main')

@section('title')
    {{ Auth::user()->name }} - @parent
@stop

@section('content')
    <main class="account">

        <div class="banner">
            <h3 class="banner__text">Добро пожаловать!</h3>
        </div>

        <nav class="navbar">
            <ul class="navbar__list">
                <li class="navbar__item">
                    <a class="navbar__link" href="{{ route('profile.index') }}">Профиль</a>
                </li>
                <li class="navbar__item">
                    <a class="navbar__link" href="#">Мои города</a>
                </li>
                <li class="navbar__item">
                    <a class="navbar__link" href="#">Мои поездки</a>
                </li>
                <li class="navbar__item">
                    <a class="navbar__link" href="#">Мои попутчики</a>
                </li>
                {{-- <li class="navbar__item">
                    <a class="navbar__link" href="{{ route('index') }}">Вернуться на главную</a>
                </li> --}}
            </ul>
        </nav>

        <div class="account__container">

            <div class="account__card grid-col-1-2">
                <div>
                    <img src="/images/face.jpg" class="avatar" alt="{{ $user->name }}">
                    <h2>{{ $user->name }}</h2>
                    <h5>{{ $user->email }}</h5>
                </div>
                <div>
                    <div class="wrapper">
                        @if(isset($dataCurrentTrips[0]))
                            <h2 class="title">Действующие поездки</h2>
                            @foreach($dataCurrentTrips as $trip)
                                <div class="current-block wrapper">
                                    <p>Город отправления: <span>{{$trip['departureCity']}}</span></p>
                                    <p>Город прибытия: <span>{{$trip['cityOfArrival']}}</span></p>
                                    <p>Период: с <span> {{$trip['start']}}</span> - по
                                        <span>{{$trip['finish']}}</span></p>
                                    @foreach($trip['roles'] as $key => $role)
                                        <div class="current-block__item">
                                            <p>Роль: {{$role}} </p>

                                            <form method="POST" class="presentation-block__form"
                                                  action="{{route('joint-update', $trip['trip'])}}">
                                                @csrf
                                                @method('PUT')

                                                <input hidden
                                                       type="text"
                                                       name="{{$key}}"
                                                       value="">


                                                <button type="submit"
                                                        class="block-form__button">
                                                    отказаться от поездки
                                                </button>
                                            </form>
                                        </div>

                                    @endforeach
                                </div>
                            @endforeach
                        @else
                            <h2 class="title">У вас незапланированно поездок</h2>
                        @endif
                    </div>

                    <div class="wrapper">
                        @if(isset($dataArchiveTrips[0]))
                            <h2 class="title">Архив поездок</h2>

                            <div class="archive-block">
                                @foreach($dataArchiveTrips as $trip)
                                    <div class="archive-block__item">
                                        <p>{{$trip['departureCity']}} - {{$trip['cityOfArrival']}}</p>
                                        <p>с <span> {{$trip['start']}}</span> - по
                                            <span>{{$trip['finish']}}</span></p>
                                        @foreach($trip['roles'] as $role)
                                            <p>Роль: {{$role}} </p>
                                        @endforeach
                                    </div>
                                @endforeach
                            </div>
                        @else
                            <h2 class="title">У вас нет поездок в архиве</h2>
                        @endif
                    </div>
                </div>


            </div>

        </div>
    </main>
@endsection

resources/views/destination.blade.php
@extends('layouts.main')

@section('title')
    {{$destination_data->name}} - @parent
@stop

@section('content')
    <main>

        <div class="destination">
            @isset($destination_data->images[0])
                <img class="destination__photo" src="{{ asset($destination_data->images[0]['name']) }}" alt="">
            @endisset
            <div class="destination__description">
                <h1 class="destination__title">
                    {{$destination_data->name}}
                </h1>
                <h2 class="destination__text">
                    {{$destination_data->description}}
                </h2>
            </div>
        </div>

        @isset($destination_data->images[0])
            <div class="carousel wrapper">
                <h2 class="title">Что вы можете увидеть посетив "{{$destination_data->name}}" </h2>
                <carousel type="{{ class_basename($destination_data::class) }}"
                          id="{{ $destination_data->id }}"></carousel>
            </div>
        @endisset


        <div class="container wrapper">
            @isset($destination_data->articles[0])
                <article>
                    {!! Storage::get('public/articles/' . $destination_data->articles[0]->article_body) ??
                    $destination_data->articles[0]->article_body !!}
                </article>
            @endisset
        </div>

        <section class="presentation container wrapper">

            @foreach($sights as $sight)

                <div class="presentation-block">
                    @isset($sight->images[0])
                        <img class="presentation-block__photo" src="{{$sight->images[0]['name']}}"
                             alt="фотография города">
                    @endisset
                    <div class="presentation-block__text">
                        {{$sight->name}}
                    </div>
                    <div class="presentation-block__hover">
                        <a class="presentation-block__hover_link"
                           href="{{route('sights.index',['city'=>$citySlug, 'sight'=>$sight->slug])}}">
                            <h3>{{$sight->description}}</h3>
                        </a>
                    </div>
                </div>
            @endforeach

        </section>

        <section class="destination-invitation">
            <div class="destination-invitation__advert">
                <div class="container">
                    @unless (Auth::check())
                        <h2>
                            Отправляйтесь в путешествие прямо сейчас! <br>
                            Выбирайте привлекательные города России, комбинируйте их в маршруты, и посетите проверенные
                            достопримечательности в нескучной компании случайных попутчиков!
                        </h2>
                        <a class="destination-invitation__advertlink" href="{{ route('login') }}">
                            Только зарегистрируйтесь!
                        </a>
                        <h2>
                            Счастливых путешествий и новых открытий!
                        </h2>
                    @else
                        <h2>
                            Вы уже с нами!
                        </h2>
                        <form method="POST" action="{{route('joint-trip')}}">
                            @csrf
                            <input type="hidden" name="departure_city_name" value="{{$departureCityName}}">

                            <input type="hidden" name="city_of_arrival_name" value="{{$cityArrivalName}}">

                            <button class="destination-invitation__advertlink">
                                Выберите маршрут и попутчика прямо сейчас!
                            </button>
                        </form>

                    @endunless
                </div>


            </div>
        </section>

        <div class="feedback-block">
            @if($comments)
                <h2 class="title">Отзывы наших пользователей</h2>

                <div class="feedback-block__items container">

                    @foreach($comments as $comment)
                        <div class="feedback-block__item">
                            <p class="feedback-block__text text">{{$comment['comment_body']}}</p>
                            <p class="feedback-block__author">{{$comment['firstname']}} {{$comment['lastname']}}</p>
                        </div>
                    @endforeach
                </div>

            @elseif(Auth::check())

                <h2>Еще ни кто не написал отзыв.</h2>
                <h2>Стань первым.</h2>
            @else

                <h2>Еще ни кто не написал отзыв.</h2>
                <a class="feedback-block__link" href="{{ route('login') }}">
                    Зарегистрируйтесь!
                </a>
                <h2>И станьте первым.</h2>

            @endif
        </div>
    </main>

@endsection

resources/views/jointTrip.blade.php
@extends('layouts.main')

@section('title')
    Совместные поездки - @parent
@stop

@section('content')
    <main>

        <div class="trip">

            <h1 class="trip__title title trip__title_mb100">
                Совместные поездки
            </h1>

            <div class="trip-description container">

                <p>Россия большая многообразная страна.</p>
                <p>Мы стремимся рассказать и виртуально показать красоту нашей родины, пробудить
                    интерес к путешествию.</p>
                <p>Способствовать встрече людей желающих посетить понравившееся место.</p>
                <p>Вы, наши соотечественники, можете помочь друг другу в познании её</p>

            </div>

        </div>

        <div class="container wrapper">
            <h2 class="title">Вы можете продолжить регистрацию</h2>
            <form method="POST" class="block-form block-form_mb" action="{{route('joint.store')}}">
                @csrf

                <input name="departure_city" type="text"
                       class="block-form__input @error('departure_city') block-form__input_error @enderror"
                       placeholder="Город отправления*"
                       value="{{$departureCity}}"
                />

                @error('departure_city')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror

                <input name="city_of_arrival" type="text"
                       class="block-form__input @error('city_of_arrival') block-form__input_error @enderror"
                       placeholder="Город прибытия*"
                       value="{{$cityOfArrival}}"
                />

                @error('city_of_arrival')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror

                <h3>В каком качестве вы желаете путешествовать</h3>
                <label class="presentation-block__form_label">
                    <input hidden
                           type="checkbox"
                           name="driver"
                           checked
                           value="{{$userId}}">
                    <span class="block-form__role-user">водителя</span>
                </label>

                <label class="presentation-block__form_label">
                    <input hidden type="checkbox" name="passenger_first" value="{{$userId}}">
                    <span class="block-form__role-user">1-го пассажира</span>
                </label>

                <label class="presentation-block__form_label">
                    <input hidden type="checkbox" name="passenger_two" value="{{$userId}}">
                    <span class="block-form__role-user">2-го пассажира</span>
                </label>

                <label class="presentation-block__form_label">
                    <input hidden type="checkbox" name="passenger_three" value="{{$userId}}">
                    <span class="block-form__role-user">3-го пассажира</span>
                </label>


                <h3>Укажите период путешествия</h3>

                <label>
                    <span>Начало путешествия</span>
                    <input class="block-form__input" type="date" name="start">
                </label>

                @error('start')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror

                <label>
                    <span>Окончание путешествия</span>
                    <input class="block-form__input" type="date" name="finish">
                </label>

                @error('finish')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror

                <button type="submit"
                        class="block-form__button">
                    Зарегистрировать поездку
                </button>
            </form>

            @isset($dataTrips[0])
                <h2 class="title">Или присоединиться к одной из существующих поездок</h2>
                <div class="presentation presentation_trip">
                    @foreach($dataTrips as $dataTrip)
                        <div class="presentation-block">
                            <img class="presentation-block__photo" src="{{$dataTrip['PhotoCityOfArrival']}}"
                                 alt="фотография города">
                            <div class="presentation-block__people">
                                <h3 class="title">{{$dataTrip['departureCity']}} - {{$dataTrip['cityOfArrival']}}</h3>
                                <h3>Период</h3>
                                <p>с <span> {{$dataTrip['start']}}</span> - по <span>{{$dataTrip['finish']}}</span></p>

                                <p>Водитель:
                                    <span>{{$dataTrip['driverFirstname'] ?: 'место свободно'}} {{$dataTrip['driverLastname']?:''}}</span>
                                </p>

                                <p>Пассажир:
                                    <span>{{$dataTrip['passengerFirstFirstname'] ?: 'место свободно'}} {{$dataTrip['passengerFirstLastname']?:''}}</span>
                                </p>

                                <p>Пассажир:
                                    <span>{{$dataTrip['passengerTwoFirstname'] ?: 'место свободно'}} {{$dataTrip['passengerTwoLastname']?:''}}</span>
                                </p>

                                <p>Пассажир:
                                    <span>{{$dataTrip['passengerThreeFirstname'] ?: 'место свободно'}} {{$dataTrip['passengerThreeLastname']?:''}}</span>
                                </p>

                            </div>

                            <div class="presentation-block__hover presentation-block__hover_trip">
                                @if($dataTrip['driverName']
                                 && $dataTrip['passengerFirstName']
                                 && $dataTrip['passengerTwoName']
                                 && $dataTrip['passengerThreeName'])
                                    <p>Свободных мест нет</p>
                                @else
                                    <h2>Желаю присоединиться в качестве:</h2>
                                    <form method="POST" class="presentation-block__form"
                                          action="{{route('joint.update', $dataTrip['trip'])}}">
                                        @csrf
                                        @method('PUT')
                                        @if(empty($dataTrip['driverName']))
                                            <label class="presentation-block__form_label">
                                                <input hidden
                                                       type="checkbox"
                                                       name="driver"
                                                       value="{{$userId}}">
                                                <span>водителя</span>
                                            </label>
                                        @endif

                                        @if(empty($dataTrip['passengerFirstName']))
                                            <label class="presentation-block__form_label">
                                                <input hidden type="checkbox" name="passenger_first"
                                                       value="{{$userId}}">
                                                <span>1-го пассажира</span>
                                            </label>
                                        @endif

                                        @if(empty($dataTrip['passengerTwoName']))
                                            <label class="presentation-block__form_label">
                                                <input hidden type="checkbox" name="passenger_two" value="{{$userId}}">
                                                <span>2-го пассажира</span>
                                            </label>
                                        @endif

                                        @if(empty($dataTrip['passengerThreeName']))
                                            <label class="presentation-block__form_label">
                                                <input hidden type="checkbox" name="passenger_three"
                                                       value="{{$userId}}">
                                                <span>3-го пассажира</span>
                                            </label>
                                        @endif
                                        <button type="submit"
                                                class="block-form__button">
                                            Присоединиться к поездке
                                        </button>
                                    </form>
                                @endif
                            </div>
                        </div>
                    @endforeach
                </div>

            @endisset
        </div>


        <div class="feedback-block">

            <h2 class="title">Отзывы наших пользователей</h2>

            <div class="feedback-block__items container">

                @foreach($comments as $comment)
                    <div class="feedback-block__item">
                        <p class="feedback-block__text text">{{$comment['object']}}</p>
                        <p class="feedback-block__text text">{{$comment['comment_body']}}</p>
                        <p class="feedback-block__author">{{$comment['firstname']}} {{$comment['lastname']}}</p>
                    </div>
                @endforeach

            </div>

        </div>

    </main>

@endsection

resources/views/trip.blade.php
@extends('layouts.main')

@section('title')
    Совместные поездки - @parent
@stop

@section('content')
    <main>

        <div class="trip">

            <h1 class="trip__title title trip__title_mb100">
                Совместные поездки
            </h1>

            <div class="trip-description container">

                <p>Россия большая многообразная страна.</p>
                <p>Мы стремимся рассказать и виртуально показать красоту нашей родины, пробудить
                    интерес к путешествию.</p>
                <p>Способствовать встрече людей желающих посетить понравившееся место.</p>
                <p>Вы, наши соотечественники, можете помочь друг другу в познании её</p>

            </div>

            <div class="trip-rules container">
                <h2 class="trip__title title"> Воспользовавшись сайтом вы можете:</h2>
                <div class="trip-rules__items">
                    <div class="trip-rules__item">
                        <p>найти попутчика для посещения города, </p>
                        <p>разделить ваши расходы на поездку с попутчиками, </p>

                    </div>
                    <div class="trip-rules__item">
                        <p>видеть будущих попутчиков </p>
                        <p>почитать отзывы о будущих попутчиках </p>
                    </div>
                    <div class="trip-rules__item">
                        <p>оставить свой отзыв о попутчиках </p>
                        <p>оставить свой отзыв о посещенном городе </p>
                    </div>

                </div>

            </div>
        </div>

        <div class="block-form trip-form container">

            <h2 class="title">Регистрация поездки</h2>

            <form method="POST" action="{{route('joint-trip')}}">
                @csrf

                @error('departure_city_name')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror

                @error('city_of_arrival_name')
                <p class="block-form__text-error">{{ $message }}</p>
                @enderror

                <select-city></select-city>

                <button type="submit"
                        class="block-form__button">
                    Продолжить регистрацию
                </button>

            </form>
        </div>

        @isset($dataTrips)

            <div class="presentation container wrapper presentation_trip">
                @foreach($dataTrips as $dataTrip)
                    <div class="presentation-block presentation-block_trip">
                        <img class="presentation-block__photo" src="{{$dataTrip['PhotoCityOfArrival']}}"
                             alt="фотография города">
                        <div class="presentation-block__people">
                            <h3 class="title">{{$dataTrip['departureCity']}} - {{$dataTrip['cityOfArrival']}}</h3>

                            <h3>Период</h3>
                            <p>с <span> {{$dataTrip['start']}}</span> - по <span>{{$dataTrip['finish']}}</span></p>

                            <p>Водитель:
                                <span>{{$dataTrip['driverFirstname'] ?: 'место свободно'}} {{$dataTrip['driverLastname']?:''}}</span>
                            </p>

                            <p>Пассажир:
                                <span>{{$dataTrip['passengerFirstFirstname'] ?: 'место свободно'}} {{$dataTrip['passengerFirstLastname']?:''}}</span>
                            </p>

                            <p>Пассажир:
                                <span>{{$dataTrip['passengerTwoFirstname'] ?: 'место свободно'}} {{$dataTrip['passengerTwoLastname']?:''}}</span>
                            </p>

                            <p>Пассажир:
                                <span>{{$dataTrip['passengerThreeFirstname'] ?: 'место свободно'}} {{$dataTrip['passengerThreeLastname']?:''}}</span>
                            </p>

                        </div>

                        <div class="presentation-block__hover presentation-block__hover_trip">
                            @if($dataTrip['driverName']
                                 && $dataTrip['passengerFirstName']
                                 && $dataTrip['passengerTwoName']
                                 && $dataTrip['passengerThreeName'])
                                <p>Свободных мест нет</p>

                            @else
                                <h2>Желаю присоединиться в качестве:</h2>
                                <form method="POST" class="presentation-block__form"
                                      action="{{route('joint.update', $dataTrip['trip'])}}">
                                    @csrf
                                    @method('PUT')
                                    @if(empty($dataTrip['driverName']))
                                        <label class="presentation-block__form_label">
                                            <input hidden
                                                   type="checkbox"
                                                   name="driver"
                                                   value="{{$userId}}">
                                            <span>водителя</span>
                                        </label>
                                    @endif

                                    @if(empty($dataTrip['passengerFirstName']))
                                        <label class="presentation-block__form_label">
                                            <input hidden type="checkbox" name="passenger_first" value="{{$userId}}">
                                            <span>1-го пассажира</span>
                                        </label>
                                    @endif

                                    @if(empty($dataTrip['passengerTwoName']))
                                        <label class="presentation-block__form_label">
                                            <input hidden type="checkbox" name="passenger_two" value="{{$userId}}">
                                            <span>2-го пассажира</span>
                                        </label>
                                    @endif

                                    @if(empty($dataTrip['passengerThreeName']))
                                        <label class="presentation-block__form_label">
                                            <input hidden type="checkbox" name="passenger_three" value="{{$userId}}">
                                            <span>3-го пассажира</span>
                                        </label>
                                    @endif
                                    <button type="submit"
                                            class="block-form__button">
                                        Присоединиться к поездке
                                    </button>
                                </form>
                            @endif
                        </div>
                    </div>
                @endforeach
            </div>

        @endisset

        {{--        <x-travel-card :dataTrips={{$dataTrips}} :userId="{{$userId}}"/>--}}

        <div class="feedback-block">

            <h2 class="title">Отзывы наших пользователей</h2>

            <div class="feedback-block__items container">

                @foreach($comments as $comment)
                    <div class="feedback-block__item">
                        <p class="feedback-block__text text">{{$comment['object']}}</p>
                        <p class="feedback-block__text text">{{$comment['comment_body']}}</p>
                        <p class="feedback-block__author">{{$comment['firstname']}} {{$comment['lastname']}}</p>
                    </div>
                @endforeach

            </div>

        </div>

    </main>

@endsection