routes/web.php
<?php

use App\Http\Controllers\JointTripController;
use App\Http\Controllers\JointTripIndexController;
use App\Http\Controllers\JointTripUpdateController;
use App\Http\Controllers\TripController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CityController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\SightController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Api\CityController as ApiCityController;
use App\Http\Controllers\Api\CarouselCityController as ApiCarouselCityController;
use App\Http\Controllers\Api\CarouselSightController as ApiCarouselSightController;
use App\Http\Controllers\Api\ImageController as ApiImageController;
use App\Http\Controllers\Admin\CityController as AdminCityController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\ImageController as AdminImageController;
use App\Http\Controllers\Admin\SightController as AdminSightController;
use App\Http\Controllers\Admin\ArticleController as AdminArticleController;
use App\Http\Controllers\Admin\CommentController as AdminCommentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::view('/', 'index')->name('index');

Route::group(['middleware' => 'auth'], function () {

    Route::match(['get', 'post'], '/account', [AccountController::class, 'index'])->name('account');
    Route::match(['get', 'post'], '/account/profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::get('/account/trip', [AccountController::class, 'trip'])->name('account.trip');
    Route::match(['get', 'post'], '/profile', [ProfileController::class, 'store'])->name('profile.store');
    Route::match(['get', 'post'], '/driver', [DriverController::class, 'store'])->name('driver.store');

    Route::get('/trip', [TripController::class, 'index'])->name('trip');
    Route::post('/trip-registration', [JointTripIndexController::class, 'index'])->name('joint-trip');
    Route::put('/trip-registration/{id}', [JointTripUpdateController::class, 'update'])->name('joint-update');
    Route::resource('/joint', JointTripController::class);
    Route::post('/comments', [CommentController::class, 'store'])->name('comments.store');

    Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
        Route::get('/', function () {
            return redirect()->route('admin.cities.index');
        })->name('index');
        Route::resource('/cities', AdminCityController::class)->except(['show']);
        Route::resource('/sights', AdminSightController::class)->except(['show']);
        Route::resource('/articles', AdminArticleController::class)->except(['show']);
        Route::resource('/images', AdminImageController::class)->except(['show', 'edit', 'update']);
        Route::resource('/users', AdminUserController::class)->except(['show']);
        Route::resource('/comments', AdminCommentController::class)->only(['index', 'destroy']);
    });
});

Route::group(['as' => 'api.', 'prefix' => 'api'], function () {
    Route::get('/cities', [ApiCityController::class, 'index']);
    Route::get('/cityList', [ApiCityController::class, 'cityList']);
    Route::get('/carousel/City/{id}', [ApiCarouselCityController::class, 'index']);
    Route::get('/carousel/Sight/{id}', [ApiCarouselSightController::class, 'index']);
    Route::post('/images/store', [ApiImageController::class, 'store'])->name('images.store');
});

Route::group(['as' => 'cities.', 'prefix' => 'cities'], function () {
    Route::get('/{city:slug}', [CityController::class, 'index'])->name('index');
});

Route::group(['as' => 'sights.', 'prefix' => 'cities'], function () {
    Route::get('/{city:slug}/{sight:slug}', [SightController::class, 'index'])->name('index');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    const TITLE = 'Пользователь';
    const TABLE = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'is_admin' => 'boolean',
    ];

    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function commentsFromUser()
    {
        return $this->hasMany(Comment::class, 'user_id', 'id');
    }

    public function profiles()
    {
        return $this->hasMany(Profile::class);
    }

    public function drivers()
    {
        return $this->hasMany(Driver::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UserFormRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.users.index', [
            'data' => User::get([
                'id',
                'name',
                'created_at',
            ]),
            'options' => [
                'url' => "/admin/users/",
                'fields' => [
                    [
                        'id' => 'id',
                        'name' => '#ID',
                    ],
                    [
                        'id' => 'name',
                        'name' => 'Имя',
                    ],
                    [
                        'id' => 'created_at',
                        'name' => 'Дата добавления',
                    ],
                ],
                'deleteConfirmation' => "Подтвердите удаление пользователя с #ID",
                'polymorphic' => [
                    [
                        'id' => 'imageable',
                        'url' => route('admin.images.create'),
                        'type' => User::TITLE,
                        'message' => 'Загрузить фото',
                    ],
                ],
            ],
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.editor');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param UserFormRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserFormRequest $request)
    {
        // $validated = $request->validated();
        // $created = User::create($validated);

        // if ($created) {
        //     return to_route('admin.users.index');
        // }

        // return back()->withInput();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.editor', [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UserFormRequest $request
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserFormRequest $request, User $user)
    {
        // $user->update($request->validated());
        // return to_route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        try {
            $user->delete();
            return response()->json('ok');
        } catch (\Exception $e) {
            \Illuminate\Support\Facades\Log::error('User error destroy', [$e]);
            return response()->json('error', 400);
        }
    }
}

resources/views/admin/users/editor.blade.php
@extends('layouts.admin')

@section('title')
    Редактор пользователя - @parent
@stop

@section('content-header')
    <h1>{{ isset($user) ? 'Редактирование информации о пользователе: ' . $user->name : 'Добавление пользователя' }}
    </h1>
@endsection

@section('content')

    <div class="block-form container">
        <form method="POST" action="{{ isset($user) ? route('admin.users.update', $user) : route('admin.users.store') }}"
            enctype="multipart/form-data">
            @csrf

            @if (isset($user))
                @method('PUT')
            @endif

            <input name="name" type="text" class="block-form__input @error('name') block-form__input_error @enderror"
                placeholder="Имя пользователя" value="{{ $user->name ?? old('name') }}" required />

            @error('name')
                <p class="block-form__text-error">{{ $message }}</p>
            @enderror

            <input name="email" type="email" class="block-form__input @error('email') block-form__input_error @enderror"
                placeholder="Электронная почта" value="{{ $user->email ?? old('email') }}" required />

            @error('email')
                <p class="block-form__text-error">{{ $message }}</p>
            @enderror

            <input name="password" type="password"
                class="block-form__input @error('password') block-form__input_error @enderror" required
                autocomplete="new-password">

            @error('password')
                <p class="block-form__text-error">{{ $message }}</p>
            @enderror

            <input name="password_confirmation" type="password"
                class="block-form__input @error('password') block-form__input_error @enderror" required
                autocomplete="new-password">

            <fieldset class="block-form__fieldset">
                <legend>Админ?</legend>
                <div>
                    <input class="form-check-input" type="radio" name="is_admin" id="is-admin" value="1"
                        @if (isset($user) && $user->is_admin === true) checked @endif>
                    <label class="form-check-label" for="is-admin">Да</label>
                </div>
                <div>
                    <input class="form-check-input" type="radio" name="is_admin" id="is-not-admin" value="0"
                        @if (isset($user) && $user->is_admin === false) checked @endif>
                    <label class="form-check-label" for="is-not-admin">Нет</label>
                </div>
            </fieldset>

            <button type="submit" class="block-form__button" value="save">
                Сохранить
            </button>
        </form>
    </div>

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('title')
    Список пользователей - @parent
@stop

@section('content-header')
    <h1>Список пользователей</h1>
    <a href="{{ route('admin.users.create') }}" class="admin-panel__button">
        Добавить пользователя
    </a>
@endsection

@section('content')
    <admin-table :data="{{ json_encode($data) }}" :options="{{ json_encode($options) }}">
    </admin-table>
@endsection