routes/web.php
<?php

use App\Http\Controllers\JointTripController;
use App\Http\Controllers\JointTripIndexController;
use App\Http\Controllers\JointTripUpdateController;
use App\Http\Controllers\TripController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CityController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\SightController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Api\CityController as ApiCityController;
use App\Http\Controllers\Api\CarouselCityController as ApiCarouselCityController;
use App\Http\Controllers\Api\CarouselSightController as ApiCarouselSightController;
use App\Http\Controllers\Api\ImageController as ApiImageController;
use App\Http\Controllers\Admin\CityController as AdminCityController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\ImageController as AdminImageController;
use App\Http\Controllers\Admin\SightController as AdminSightController;
use App\Http\Controllers\Admin\ArticleController as AdminArticleController;
use App\Http\Controllers\Admin\CommentController as AdminCommentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::view('/', 'index')->name('index');

Route::group(['middleware' => 'auth'], function () {

    Route::match(['get', 'post'], '/account', [AccountController::class, 'index'])->name('account');
    Route::match(['get', 'post'], '/account/profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::get('/account/trip', [AccountController::class, 'trip'])->name('account.trip');
    Route::match(['get', 'post'], '/profile', [ProfileController::class, 'store'])->name('profile.store');
    Route::match(['get', 'post'], '/driver', [DriverController::class, 'store'])->name('driver.store');

    Route::get('/trip', [TripController::class, 'index'])->name('trip');
    Route::post('/trip-registration', [JointTripIndexController::class, 'index'])->name('joint-trip');
    Route::put('/trip-registration/{id}', [JointTripUpdateController::class, 'update'])->name('joint-update');
    Route::resource('/joint', JointTripController::class);
    Route::post('/comments', [CommentController::class, 'store'])->name('comments.store');

    Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
        Route::get('/', function () {
            return redirect()->route('admin.cities.index');
        })->name('index');
        Route::resource('/cities', AdminCityController::class)->except(['show']);
        Route::resource('/sights', AdminSightController::class)->except(['show']);
        Route::resource('/articles', AdminArticleController::class)->except(['show']);
        Route::resource('/images', AdminImageController::class)->except(['show', 'edit', 'update']);
        Route::resource('/users', AdminUserController::class)->except(['show']);
        Route::resource('/comments', AdminCommentController::class)->only(['index', 'destroy']);
    });
});

Route::group(['as' => 'api.', 'prefix' => 'api'], function () {
    Route::get('/cities', [ApiCityController::class, 'index']);
    Route::get('/cityList', [ApiCityController::class, 'cityList']);
    Route::get('/carousel/City/{id}', [ApiCarouselCityController::class, 'index']);
    Route::get('/carousel/Sight/{id}', [ApiCarouselSightController::class, 'index']);
    Route::post('/images/store', [ApiImageController::class, 'store'])->name('images.store');
});

Route::group(['as' => 'cities.', 'prefix' => 'cities'], function () {
    Route::get('/{city:slug}', [CityController::class, 'index'])->name('index');
});

Route::group(['as' => 'sights.', 'prefix' => 'cities'], function () {
    Route::get('/{city:slug}/{sight:slug}', [SightController::class, 'index'])->name('index');
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
    use HasFactory, SoftDeletes;

    const TITLE = 'Статья';
    const TABLE = 'articles';

    protected $fillable = [
        'user_id',
        'title',
        'description',
        'article_body',
        'articleable_id',
        'articleable_type',
    ];

    public function users()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function articleable()
    {
        return $this->morphTo();
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\City;
use App\Models\Sight;
use App\Models\Article;
use App\Services\UploadService;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ArticleFormRequest;
use App\Services\ModelService;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.articles.index', [
            'data' => Article::get([
                'id',
                'title',
                'created_at',
            ]),
            'options' => [
                'url' => "/admin/articles/",
                'fields' => [
                    [
                        'id' => 'id',
                        'name' => '#ID',
                    ],
                    [
                        'id' => 'title',
                        'name' => 'Название',
                    ],
                    [
                        'id' => 'created_at',
                        'name' => 'Дата добавления',
                    ],
                ],
                'deleteConfirmation' => "Подтвердите удаление статьи с #ID",
            ],
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view(
            'admin.articles.editor',
            ['relations' => app(ModelService::class)->getRelationsByMethod("articles", ['id', 'name'])]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ArticleFormRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleFormRequest $request)
    {
        $validated = $request->validated();

        try {
            $articleable = app(ModelService::class)
                ->getModelNameSpaceByTitle($validated['articleable_type'])
                ::find($validated['articleable_id']);

            $articles = [
                new Article([
                    'article_body' => app(UploadService::class)->saveText(
                        $validated['article_body'],
                        'articles',
                    ),
                    'user_id' => $validated['user_id'],
                    'title' => $validated['title'],
                    'description' => $validated['description'],
                ])
            ];
            $articleable->articles()->saveMany($articles);

            return to_route('admin.articles.index');
        } catch (\Exception $e) {
            return back()->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('admin.articles.editor', [
            'article' => $article,
            'relations' => app(ModelService::class)->getRelationsByMethod("articles", ['id', 'name']),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ArticleFormRequest $request
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleFormRequest $request, Article $article)
    {
        $validated = $request->validated();
        unset($validated['articleable_type']);
        $validated['article_body'] = app(UploadService::class)->saveText(
            $validated['article_body'],
            'articles',
            $article->article_body,
        );
        $updated = $article->fill($validated)->save();
        if ($updated) {
            return to_route('admin.articles.index');
        }
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        try {
            $article->delete();
            return response()->json('ok');
        } catch (\Exception $e) {
            \Illuminate\Support\Facades\Log::error('Article error destroy', [$e]);
            return response()->json('error', 400);
        }
    }
}

resources/views/admin/articles/editor.blade.php
@extends('layouts.admin')

@section('title')
    Редактор статьи - @parent
@stop

@section('content-header')
    <h1>{{ isset($article) ? 'Редактирование статьи: ' . $article->title : 'Добавление статьи' }}</h1>
@endsection

@section('content')
    <div class="block-form container">
        <form method="POST"
            action="{{ isset($article) ? route('admin.articles.update', $article) : route('admin.articles.store') }}"
            enctype="multipart/form-data">
            @csrf

            @if (isset($article))
                @method('PUT')
            @endif

            <input type="hidden" name="user_id" id="userId" value="{{ Auth::user()->id }}">

            <select-relation relation-name="articleable" :relations="{{ json_encode($relations) }}"
                selected-type="{{ isset($article) ? ($article->articleable_type)::TITLE : request()->get('articleable_type') }}"
                selected-id="{{ isset($article) ? $article->articleable_id : request()->get('articleable_id') }}">
            </select-relation>

            @error('articleable_type')
                <p class="block-form__text-error">{{ $message }}</p>
            @enderror

            @error('articleable_id')
                <p class="block-form__text-error">{{ $message }}</p>
            @enderror

            <input name="title" type="text" class="block-form__input @error('title') block-form__input_error @enderror"
                placeholder="Заголовок" value="{{ $article->title ?? old('title') }}" />

            @error('title')
                <p class="block-form__text-error">{{ $message }}</p>
            @enderror

            <input name="description" type="text"
                class="block-form__input @error('description') block-form__input_error @enderror"
                placeholder="Краткое описание" value="{{ $article->description ?? old('description') }}" />

            @error('description')
                <p class="block-form__text-error">{{ $message }}</p>
            @enderror

            <textarea name="article_body" id="editor">
            {!! isset($article) ? Storage::get('public/articles/' . $article->article_body) : old('article_body') !!}
        </textarea>

            @error('article_body')
                <p class="block-form__text-error">{{ $message }}</p>
            @enderror

            <button type="submit" class="block-form__button" value="save">
                Сохранить
            </button>
        </form>
    </div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.admin')

@section('title')
Список статей - @parent
@stop

@section('content-header')
<h1>Список статей</h1>
<a href="{{ route('admin.articles.create') }}" class="admin-panel__button">
    Добавить статью
</a>
@endsection

@section('content')
    <admin-table :data="{{ json_encode($data) }}" :options="{{ json_encode($options) }}">
    </admin-table>
@endsection